name: Python Linter

on:
  push:
    branches: [ "main" ]
    paths:
      - para_bulkupdate.py
      - pyproject.toml
      - uv.lock
  pull_request:
    branches: [ "main" ]
    paths:
      - para_bulkupdate.py
      - pyproject.toml
      - uv.lock

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python 3.12
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.12

      - name: Install Ruff
        uses: astral-sh/ruff-action@v3.2.1

      - name: Check code style
        run: ruff check

      - name: Check formatting
        run: ruff format --check
